### PR TITLE
SNK-34: Pagination for List Product

### PR DESCRIPTION
**Pull request by quoctrang-le**
I've finished this task, please check it!!!
image

### CODE REVIEW

**Comment by thangduongnfq** [comment]
too ugly !! 
image

**Review by thangduongnfq — APPROVED** [review]
not beautiful as I expect bro !! i think you should remove it

**Comment by quoctrang-le** [comment]
@lcnhut what do you think with @thangduongnfq's response

**Comment by lcnhut** [comment]
> @lcnhut what do you think with @thangduongnfq's response

I think it's ok. Not really ugly, we need this function for user

**Review by lcnhut — APPROVED** [review]
You did it well!

**Pull request merged**
