### PR TITLE
SNK-23: Create details page

### PR DESCRIPTION
**Pull request by quoctrang-le**
I've deleted the button add to cart and change some styles please check it

image

### CODE REVIEW

**Comment by thangduongnfq** [comment]
image

image


your list of the product has a problem

**Comment by quoctrang-le** [comment]
ok I'll check it

**Comment by quoctrang-le** [comment]
its oke now

image

**Review by thangduongnfq — APPROVED** [review]
oke, nice bro !!

**Review by lcnhut — APPROVED** [review]
You did it well! But very too so much LÂU!!!

**Pull request merged**
