### PR TITLE
SNK-41: Write unit test for invoice slice

### PR DESCRIPTION
**Pull request by quoctrang-le**
I've wrote unit test for invoice slice, please check it
image

image

### CODE REVIEW

**Review by thangduongnfq — DISMISSED** [review]
oke that nice !!

**Review by thangduongnfq — COMMENTED** [review]
Change your PR into testing

**Review by thangduongnfq — APPROVED** [review]
oke, you did well !!

**Review by lcnhut — APPROVED** [review]
I think you did it well!

**Pull request merged**
